// PengoTarot/Powers/PlanetMarsPower.cs
#nullable enable
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Entities.Powers;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.Platform;
using MegaCrit.Sts2.Core.Runs;

namespace PengoTarot.Powers
{
    public sealed class PlanetMarsPower : PowerModel
    {
        public List<Player> PairedPlayers { get; set; } = new();
        public bool Syncing { get; set; }

        public override PowerType Type => PowerType.Buff;
        public override PowerStackType StackType => PowerStackType.Single;

        protected override IEnumerable<DynamicVar> CanonicalVars =>
            new[] { new StringVar("PairedName") };

        public void RefreshPairedName()
        {
            if (PairedPlayers.Count == 0) return;
            var names = PairedPlayers
                .Select(p => PlatformUtil.GetPlayerName(RunManager.Instance.NetService.Platform, p.NetId));
            ((StringVar)DynamicVars["PairedName"]).StringValue = string.Join(", ", names);
        }

        public override Task AfterApplied(Creature? applier, CardModel? cardSource)
        {
            RefreshPairedName();
            return Task.CompletedTask;
        }

        /// <summary>
        /// When the power owner generates a card for combat (shivs, potion cards, etc.),
        /// clone it and add to all paired players.
        /// Only triggers on cards generated by the owner, not cards given by enemies
        /// (enemies pass null as creator).
        /// </summary>
        public override async Task AfterCardGeneratedForCombat(CardModel card, Player? creator)
        {
            if (Syncing || PairedPlayers.Count == 0) return;
            if (creator != Owner?.Player) return;

            Syncing = true;
            foreach (var p in PairedPlayers)
            {
                var pp = p.Creature.GetPower<PlanetMarsPower>();
                if (pp != null) pp.Syncing = true;
            }

            foreach (var paired in PairedPlayers)
            {
                var clone = CreateCloneForPlayer(card, paired);
                CardCmd.PreviewCardPileAdd(
                    await CardPileCmd.AddGeneratedCardToCombat(
                        clone,
                        card.Pile?.Type ?? PileType.Hand,
                        paired
                    )
                );
            }

            foreach (var p in PairedPlayers)
            {
                var pp = p.Creature.GetPower<PlanetMarsPower>();
                if (pp != null) pp.Syncing = false;
            }
            Syncing = false;
            Flash();
        }

        /// <summary>
        /// When the power owner channels an orb, channel a copy for all paired players.
        /// </summary>
        public override async Task AfterOrbChanneled(PlayerChoiceContext choiceContext, Player player, OrbModel orb)
        {
            if (Syncing || PairedPlayers.Count == 0) return;
            if (player != Owner?.Player) return;

            Syncing = true;
            foreach (var p in PairedPlayers)
            {
                var pp = p.Creature.GetPower<PlanetMarsPower>();
                if (pp != null) pp.Syncing = true;
            }

            foreach (var paired in PairedPlayers)
            {
                var clone = ModelDb.GetById<OrbModel>(orb.Id).ToMutable();
                await OrbCmd.Channel(choiceContext, clone, paired);
            }

            foreach (var p in PairedPlayers)
            {
                var pp = p.Creature.GetPower<PlanetMarsPower>();
                if (pp != null) pp.Syncing = false;
            }
            Syncing = false;
            Flash();
        }

        /// <summary>
        /// When the power owner summons, summon for all paired players.
        /// </summary>
        public override async Task AfterSummon(PlayerChoiceContext choiceContext, Player summoner, decimal amount)
        {
            if (Syncing || PairedPlayers.Count == 0) return;
            if (summoner != Owner?.Player) return;

            Syncing = true;
            foreach (var p in PairedPlayers)
            {
                var pp = p.Creature.GetPower<PlanetMarsPower>();
                if (pp != null) pp.Syncing = true;
            }

            foreach (var paired in PairedPlayers)
                await OstyCmd.Summon(choiceContext, paired, amount, this);

            foreach (var p in PairedPlayers)
            {
                var pp = p.Creature.GetPower<PlanetMarsPower>();
                if (pp != null) pp.Syncing = false;
            }
            Syncing = false;
            Flash();
        }

        /// <summary>
        /// Creates a clone of the given card and assigns ownership to the specified player.
        /// Mirrors CardModel.CreateCloneForPlayer() (109) for cross-version compatibility (107).
        /// </summary>
        public static CardModel CreateCloneForPlayer(CardModel card, Player player)
        {
            var clone = card.CreateClone();
            var ownerField = typeof(CardModel).GetField("_owner",
                BindingFlags.NonPublic | BindingFlags.Instance);
            ownerField?.SetValue(clone, player);
            return clone;
        }
    }
}